// Song mithören mit Fake-Mikrofon (WAV mit bekanntem Tempo); prüft BPM, Startzeit-Offset und Export ohne Ton
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import { makeSong } from './wav.mjs';
const OUT = process.env.OUT || '/tmp/cinebeat-test';
(await import('node:fs')).mkdirSync(OUT, { recursive: true });
makeSong(`${OUT}/mic.wav`, { bpm: 118, dur: 60 });
const APP = process.env.APP || 'http://127.0.0.1:8123/index.html';
const b = await chromium.launch({ args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream', `--use-file-for-fake-audio-capture=${OUT}/mic.wav%noloop`, '--autoplay-policy=no-user-gesture-required', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, permissions: ['microphone'] });
const page = await ctx.newPage();
const errs = [];
page.on('pageerror', (e) => errs.push(e.message));
page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
await page.goto(APP);
await page.waitForSelector('.place');
await page.click('.place');
await page.waitForFunction(() => CineBeat.S.plan && document.getElementById('busy').hidden, null, { timeout: 90000 });
await page.click('#tabbtn-music');
await page.click('#micSong');
await page.fill('#micName', 'Testsong – Band');
await page.fill('#micOffset', '1:05');
await page.screenshot({ path: `${OUT}/mic_sheet.png` });
await page.click('#micGo');
await page.waitForTimeout(3000);
console.log('während:', await page.textContent('#micTime'), 'Knopf aktiv:', await page.evaluate(() => !document.getElementById('micGo').disabled));
await page.waitForFunction(() => !document.getElementById('micGo').disabled, null, { timeout: 30000 });
await page.waitForTimeout(12000);
await page.screenshot({ path: `${OUT}/mic_rec.png` });
await page.click('#micGo');
await page.waitForFunction(() => CineBeat.S.ctx.song.mic && document.getElementById('busy').hidden && CineBeat.S.plan, null, { timeout: 90000 });
await page.waitForTimeout(500);
console.log('Song:', await page.evaluate(() => { const s = CineBeat.S.ctx.song; return { name: s.name, dur: s.buffer.duration.toFixed(1), bpm: s.an.bpm.toFixed(1), sections: s.an.sections.map((x) => x.label).join(','), offset: s.offset, winStart: CineBeat.S.plan.win.start.toFixed(2) }; }));
console.log('Meta:', await page.textContent('#songMeta'));
console.log('IG:', await page.textContent('#igLine'));
console.log('Mikro frei:', await page.evaluate(() => navigator.mediaDevices.enumerateDevices().then(() => 'ok')));
await page.click('#exportBtn');
await page.waitForSelector('#qPick');
await page.waitForTimeout(800);
console.log('Export-Sheet:', await page.evaluate(() => ({ info: document.getElementById('expInfo').textContent, withDisabled: document.querySelector('#audPick [data-v="with"]').disabled, k4: !document.querySelector('#qPick [data-v="4k"]').hidden, aud: document.getElementById('audHint').textContent })));
await page.click('#qPick [data-v="max"]');
console.log('max:', await page.textContent('#expInfo'));
await page.screenshot({ path: `${OUT}/export_sheet.png` });
console.log('Fehler:', errs.join('\n') || 'keine');
await b.close();
