import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const OUT = process.env.OUT || '/tmp/cinebeat-test';
(await import('node:fs')).mkdirSync(OUT, { recursive: true });
const URL_ = process.env.APP || 'http://127.0.0.1:8123/index.html';
const browser = await chromium.launch({ args: ['--autoplay-policy=no-user-gesture-required', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
const errs = [], requests = [];
page.on('pageerror', (e) => errs.push('pageerror: ' + e.message));
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errs.push(m.type() + ': ' + m.text()); });
page.on('request', (r) => { const u = r.url(); if (!u.startsWith('blob:') && !u.startsWith('data:') && u !== URL_) requests.push(u); });
const shot = (n, full = false) => page.screenshot({ path: `${OUT}/v3ui_${n}.png`, fullPage: full });
await page.goto(URL_);
await page.waitForSelector('.place', { timeout: 30000 });
await page.waitForTimeout(400);
await shot('1_trip', true);
await page.click('.place');
await page.waitForFunction(() => CineBeat.S.plan && document.getElementById('busy').hidden, null, { timeout: 90000 });
await page.waitForTimeout(1200);
console.log('Demo-Plan:', await page.evaluate(() => { const p = CineBeat.S.plan; return { D: p.duration.toFixed(1), resolved: p.resolved, notes: p.notes }; }));
await shot('2_editor', true);
for (const tab of ['material', 'music', 'cut', 'text']) { await page.click(`[data-tab="${tab}"]`); await page.waitForTimeout(500); await shot('3_' + tab, true); }
await page.click('[data-tab="style"]');
await page.click('#fmtChips [data-v="16:9"]');
await page.waitForTimeout(1500);
await shot('4_film');
await page.click('#fmtChips [data-v="9:16"]');
await page.click('#frameChips [data-v="band"]');
await page.waitForTimeout(1500);
await shot('5_band');
await page.click('#undoBtn'); await page.waitForTimeout(800);
console.log('Undo frame ->', await page.evaluate(() => CineBeat.S.ctx.rec.settings.frame));
// neuer leerer Ort
await page.click('#backBtn'); await page.waitForSelector('.place');
await page.click('#addPlace');
await page.waitForFunction(() => CineBeat.S.ctx && CineBeat.S.plan !== undefined && document.getElementById('busy').hidden, null, { timeout: 60000 });
await page.waitForTimeout(800);
console.log('Leerer Ort: emptyStage sichtbar =', await page.evaluate(() => !document.getElementById('emptyStage').hidden));
await shot('6_empty');
await page.click('#exportBtn').catch(() => {});
console.log('Überbreite:', await page.evaluate(() => document.documentElement.scrollWidth - innerWidth));
console.log('Externe Anfragen:', requests.length ? requests : 'keine');
console.log('Fehler:', errs.length ? errs.join('\n') : 'keine');
await browser.close();
